from .constants import BarCode, BarCodePosition, CharSet, Chinese, CodePage


def validate_barcode(data: str, barcode_type: BarCode) -> None: ...
def validate_barcode_position(position: BarCodePosition) -> None: ...
def validate_charset(charset: CharSet) -> None: ...
def validate_chinese_format(fmt: Chinese) -> None: ...
def validate_codepage(codepage: CodePage) -> None: ...
