version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    assignees:
      - BoboTiG

  # Python requirements
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    assignees:
      - BoboTiG
