language: python
python:
  - 3.5
  - 3.6
  - nightly
  - pypy3

install:
  - pip install flake8 pyserial pillow
  - python setup.py develop

script:
  - python -m pytest tests
  - python -m flake8 thermalprinter
#  - python -m mypy --check-untyped-defs --warn-incomplete-stub --silent-imports -m thermalprinter
#  - python -m mypy --check-untyped-defs --warn-incomplete-stub --silent-imports thermalprinter

matrix:
  allow_failures:
    - python: nightly
