language: python
python:
  - 3.5
  - 3.6
  - nightly
  - pypy3

install:
  - pip install --upgrade flake8 pyserial pillow
  - python setup.py install

script:
  - python -m pytest --port=/dev/pts/1
  - python -m flake8 thermalprinter
#  - python -m mypy --check-untyped-defs --warn-incomplete-stub --silent-imports -m thermalprinter
#  - python -m mypy --check-untyped-defs --warn-incomplete-stub --silent-imports thermalprinter

matrix:
  allow_failures:
    - python: nightly
