name: Code quality

on: pull_request

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install requirements
        run: python -m pip install -e '.[dev]'
      - name: Imports
        run: python -m isort --check --diff thermalprinter tests
      - name: Style
        run: python -m black --check --diff thermalprinter tests
      - name: Lint
        run: python -m flake8 thermalprinter tests
      - name: Types
        run: python -m mypy thermalprinter
