name: Code quality

on: pull_request

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
      - name: Install requirements
        run: python -m pip install -e '.[dev]'
      - name: Check
        run: ./checks.sh
