name: Tests

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"
      - name: Install requirements
        run: python -m pip install -e '.[tests]'
      - name: Unit tests
        run: python -m pytest

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install requirements
        run: python -m pip install -e '.[docs]'
      - name: Check the documentation
        run: sphinx-build --color -W -bhtml docs/source docs/output
